### ISSUE TITLE
Idea Request : Discord users use speech commands in vocal channels instead of text :)

### ISSUE THREAD

**Issue by TenebrisOS** [lamHoussam/ChatGPTBot#1]
Recently i discovered how to convert microphones speech onto text, it can be used to make discord users use vocal commands instead of text as said in title. Im not sure its going to work but here are the details : 

- Create a virtual microphone where Discord users speech will be there, and with pyttsx3 module, (from this website [https://www.geeksforgeeks.org/python-convert-speech-to-text-and-text-to-speech/?ref=rp]), you can convert microphone speech into text. And then that question text will be used in chat GPT. 

Note : This is just a theory, i never tested any of this. But i hope it would work, coz its an awesome idea x)

**Comment by lamHoussam** [comment]
will work on that later :)

**Comment by TenebrisOS** [comment]
yey
